version: "3"

services:
  mariadb:
    image: mdb_compose_i
    container_name: mdb_incp
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
        - .env
    restart: always
    expose:
      - 3306
    networks:
      - inception_net
    volumes:
      - mariadb_vol:${HOME}/data/mariadb
  nginx:
    image: nginx_compose_i
    container_name: nginx_incp
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
        - .env
    # environment:
    #   - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    expose:
      - 443
      - 3306
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wp_vol:${HOME}/data/wordpress
    depends_on: 
      - mariadb

volumes:
  mariadb_vol:
  wp_vol:

networks:
  inception_net: