version: "3"

services:
  mariadb:
    image: mdb_compose_i
    container_name: mdb_incp
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        DB_NAME: ${DB_NAME}
        WP_USER: ${WP_USER}
        WP_PWD: ${WP_PWD}
        DB_PORT: ${DB_PORT}
        DB_ROOT_PWD: ${DB_ROOT_PWD}
    env_file:
        - .env
    restart: always
    expose:
      - 3306
    networks:
      - inception_net
    volumes:
      - mariadb_vol:/var/lib/mysq
    hostname: mariadb

  nginx:
    image: nginx_compose_i
    container_name: nginx_incp
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
        - .env
    restart: always
    expose:
      - 443
      - 9000
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on: 
      - wordpress
    hostname: nginx

  wordpress:
    image: wp_compose_i
    container_name: wp_incp
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        DB_NAME: ${DB_NAME}
        WP_USER: ${WP_USER}
        WP_PWD: ${WP_PWD}
        WP_PORT: ${WP_PORT}
        DB_PORT: ${DB_PORT}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PWD: ${WP_ADMIN_PWD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        DB_HOST: ${DB_HOST}
    env_file:
        - .env
    restart: always
    expose:
      - 3306
      - 9000
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on: 
      - mariadb
    hostname: wordpress

volumes:
  mariadb_vol:
  wordpress_vol:

networks:
  inception_net: