services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
        - .env
    restart: always
    expose:
      - 3306
    networks:
      - inception_net
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
        - .env
    restart: always
    expose:
      - 3306
      - 9000
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on: 
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
        - .env
    restart: always
    expose:
      - 443
      - 9000
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on: 
      - wordpress

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/db

  wordpress_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wp

networks:
  inception_net:
    external: false
    