version: "3"

services:
  mariadb:
    image: mdb_compose_i
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
        - .env
    restart: always
    expose:
      - 3306
    networks:
      - inception_net
    volumes:
      - mariadb_vol:/var/lib/mysq

  wordpress:
    image: wp_compose_i
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
        - .env
    restart: always
    expose:
      - 3306
      - 9000
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on: 
      - mariadb

  nginx:
    image: nginx_compose_i
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
        - .env
    restart: always
    expose:
      - 443
      - 9000
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wordpress_vol:/var/www/html
    depends_on: 
      - wordpress

volumes:
  mariadb_vol:
  wordpress_vol:

networks:
  inception_net: